### PR TITLE
Imported and adapted from React version

### PR DESCRIPTION
**Pull request by simongamester**

### CODE REVIEW

**Comment by tony-shannon** [comment]
lovely job @simongamester looks great

May need to add link to the Hamburger topleft,, tbc..
image

**Comment by tony-shannon** [comment]
@robtweed, please find this Helm login page now done

**Comment by simongamester** [comment]
Thanks @tony-shannon Where should the link go?

**Comment by tony-shannon** [comment]
> Thanks @tony-shannon Where should the link go?

Not sure @simongamester 

@PhilBarrett  please supply details of the linkage top left as/when available, (see above)

**Pull request merged**
